create extension if not exists pgcrypto;

create table if not exists public.waitlist (
  email text primary key check (char_length(email) <= 254),
  source text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  marketing_consent boolean not null default false,
  marketing_consent_at timestamptz,
  unsubscribed_at timestamptz,
  brevo_contact_id text,
  brevo_sync_status text not null default 'pending',
  confirmation_status text not null default 'pending',
  confirmation_sent_at timestamptz,
  signed_up_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.waitlist add column if not exists utm_source text;
alter table public.waitlist add column if not exists utm_medium text;
alter table public.waitlist add column if not exists utm_campaign text;
alter table public.waitlist add column if not exists marketing_consent_at timestamptz;
alter table public.waitlist add column if not exists unsubscribed_at timestamptz;
alter table public.waitlist add column if not exists brevo_contact_id text;
alter table public.waitlist add column if not exists brevo_sync_status text not null default 'pending';
alter table public.waitlist add column if not exists confirmation_status text not null default 'pending';
alter table public.waitlist add column if not exists confirmation_sent_at timestamptz;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  purchaser_email text not null,
  stripe_checkout_session_id text not null unique,
  stripe_customer_id text,
  stripe_payment_intent_id text,
  stripe_subscription_id text,
  stripe_price_id text not null,
  kind text not null check (kind in ('founding', 'subscription')),
  amount_total integer not null default 0,
  currency text not null default 'usd',
  status text not null check (status in ('pending', 'paid', 'failed', 'canceled', 'refunded')),
  fulfilled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_kind_status_idx on public.orders (kind, status);
create index if not exists orders_payment_intent_idx on public.orders (stripe_payment_intent_id);
create index if not exists orders_subscription_idx on public.orders (stripe_subscription_id);

create table if not exists public.stripe_events (
  event_id text primary key,
  event_type text not null,
  status text not null default 'processing' check (status in ('processing', 'processed', 'failed')),
  last_error text,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists public.email_events (
  id uuid primary key default gen_random_uuid(),
  recipient_email text not null,
  email_kind text not null,
  provider_message_id text,
  status text not null,
  attempts integer not null default 1,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists email_events_provider_id_idx on public.email_events (provider_message_id);

create table if not exists public.conversion_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('waitlist_joined', 'checkout_started', 'founding_purchase_completed', 'subscription_started', 'payment_failed', 'refund_completed', 'marketing_unsubscribed')),
  source text,
  page text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  reference_id text,
  occurred_at timestamptz not null default now()
);

create index if not exists conversion_events_name_time_idx on public.conversion_events (event_name, occurred_at desc);

create table if not exists public.api_rate_limits (
  rate_key text not null,
  bucket_start timestamptz not null,
  request_count integer not null default 1,
  primary key (rate_key, bucket_start)
);

create or replace function public.join_waitlist(p_email text, p_source text, p_utm_source text, p_utm_medium text, p_utm_campaign text, p_marketing_consent boolean)
returns table (result_email text, should_send_confirmation boolean)
language plpgsql security definer set search_path = public
as $$
declare existing_status text;
begin
  select confirmation_status into existing_status from public.waitlist where email = p_email for update;
  if found then
    update public.waitlist set
      source = coalesce(p_source, source), utm_source = coalesce(p_utm_source, utm_source),
      utm_medium = coalesce(p_utm_medium, utm_medium), utm_campaign = coalesce(p_utm_campaign, utm_campaign),
      marketing_consent = marketing_consent or p_marketing_consent,
      marketing_consent_at = case when p_marketing_consent then coalesce(marketing_consent_at, now()) else marketing_consent_at end,
      unsubscribed_at = case when p_marketing_consent then null else unsubscribed_at end,
      brevo_sync_status = case when p_marketing_consent and brevo_sync_status <> 'synced' then 'pending' else brevo_sync_status end,
      updated_at = now()
    where email = p_email;
    return query select p_email, false;
  end if;
  insert into public.waitlist (email, source, utm_source, utm_medium, utm_campaign, marketing_consent, marketing_consent_at)
  values (p_email, p_source, p_utm_source, p_utm_medium, p_utm_campaign, p_marketing_consent, case when p_marketing_consent then now() end);
  return query select p_email, true;
end;
$$;

create or replace function public.check_api_rate_limit(p_rate_key text, p_limit integer default 5, p_window_seconds integer default 60)
returns boolean language plpgsql security definer set search_path = public
as $$
declare
  current_bucket timestamptz := to_timestamp(floor(extract(epoch from now()) / p_window_seconds) * p_window_seconds);
  current_count integer;
begin
  insert into public.api_rate_limits (rate_key, bucket_start, request_count) values (p_rate_key, current_bucket, 1)
  on conflict (rate_key, bucket_start) do update set request_count = public.api_rate_limits.request_count + 1
  returning request_count into current_count;
  return current_count <= p_limit;
end;
$$;

create or replace function public.claim_stripe_event(p_event_id text, p_event_type text)
returns boolean language plpgsql security definer set search_path = public
as $$
begin
  insert into public.stripe_events (event_id, event_type, status)
  values (p_event_id, p_event_type, 'processing')
  on conflict (event_id) do nothing;
  if found then return true; end if;

  update public.stripe_events
  set status = 'processing', event_type = p_event_type, last_error = null, received_at = now(), processed_at = null
  where event_id = p_event_id and status = 'failed';
  return found;
end;
$$;

create or replace function public.record_paid_order(p_email text, p_checkout_session_id text, p_customer_id text, p_payment_intent_id text, p_subscription_id text, p_price_id text, p_kind text, p_amount_total integer, p_currency text)
returns boolean language plpgsql security definer set search_path = public
as $$
declare was_fulfilled boolean;
begin
  select fulfilled_at is not null into was_fulfilled from public.orders where stripe_checkout_session_id = p_checkout_session_id for update;
  if found then
    update public.orders set purchaser_email = p_email, stripe_customer_id = p_customer_id,
      stripe_payment_intent_id = p_payment_intent_id, stripe_subscription_id = p_subscription_id,
      stripe_price_id = p_price_id, kind = p_kind, amount_total = p_amount_total,
      currency = lower(p_currency), status = 'paid', fulfilled_at = coalesce(fulfilled_at, now()), updated_at = now()
    where stripe_checkout_session_id = p_checkout_session_id;
    return not was_fulfilled;
  end if;
  insert into public.orders (purchaser_email, stripe_checkout_session_id, stripe_customer_id, stripe_payment_intent_id, stripe_subscription_id, stripe_price_id, kind, amount_total, currency, status, fulfilled_at)
  values (p_email, p_checkout_session_id, p_customer_id, p_payment_intent_id, p_subscription_id, p_price_id, p_kind, p_amount_total, lower(p_currency), 'paid', now());
  return true;
end;
$$;

create or replace view public.conversion_summary as
select event_name, count(*)::bigint as total, min(occurred_at) as first_event_at, max(occurred_at) as latest_event_at
from public.conversion_events group by event_name;

alter table public.waitlist enable row level security;
alter table public.orders enable row level security;
alter table public.stripe_events enable row level security;
alter table public.email_events enable row level security;
alter table public.conversion_events enable row level security;
alter table public.api_rate_limits enable row level security;

-- Secret API keys use service_role, which bypasses RLS but still needs SQL privileges.
grant usage on schema public to service_role;
grant select, insert, update on public.waitlist, public.orders, public.stripe_events,
  public.email_events, public.conversion_events, public.api_rate_limits to service_role;
grant select on public.conversion_summary to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public.join_waitlist(text, text, text, text, text, boolean) from public, anon, authenticated;
revoke all on function public.check_api_rate_limit(text, integer, integer) from public, anon, authenticated;
revoke all on function public.claim_stripe_event(text, text) from public, anon, authenticated;
revoke all on function public.record_paid_order(text, text, text, text, text, text, text, integer, text) from public, anon, authenticated;
grant execute on function public.join_waitlist(text, text, text, text, text, boolean) to service_role;
grant execute on function public.check_api_rate_limit(text, integer, integer) to service_role;
grant execute on function public.claim_stripe_event(text, text) to service_role;
grant execute on function public.record_paid_order(text, text, text, text, text, text, text, integer, text) to service_role;
