import type { Metadata } from "next";
import PolicyShell from "../PolicyShell";

export const metadata: Metadata = { title: "Privacy Policy | FollowPact", description: "How FollowPact handles waitlist, preorder, product, project, analytics, and service data." };

export default function PrivacyPolicy() {
  return <PolicyShell label="Policy / Effective September 9, 2026" title="Privacy Policy" intro="FollowPact collects only the information reasonably needed to operate the waitlist, fulfill purchases, provide the product and concierge service, and understand whether the service is useful.">
    <section><h2>Information we collect</h2><p>This may include your email address, signup time, marketing preference, acquisition source, account information, preorder or subscription status, and service communications. When you use the product, it may also include the clients, projects, deadlines, invoices, time plans, outreach records, and Scope-Lock information you choose to submit.</p></section>
    <section><h2>Payments and deposits</h2><p>Stripe or another payment provider processes purchases and may provide FollowPact with payment status, customer identifiers, and limited billing details. FollowPact does not collect or hold the freelancer&apos;s client deposit through the manual Scope-Lock workflow. Freelancers create and provide their own payment links.</p></section>
    <section><h2>How information is used</h2><p>Information is used to confirm signups, deliver beta and launch access, fulfill Scope-Lock requests, provide support, secure the service, prevent abuse, improve features, measure conversions and product use, maintain financial records, and comply with legal obligations.</p></section>
    <section><h2>Service providers</h2><p>FollowPact uses Supabase to store waitlist, consent, order, email-status, and conversion records; Stripe to process payments; Brevo to send transactional and opted-in marketing email; and Cloudflare Web Analytics for privacy-first page traffic and performance reporting. Netlify hosts the website and provides deployment and function logs. These providers process only the information needed for their roles.</p></section>
    <section><h2>Analytics</h2><p>Cloudflare Web Analytics reports anonymous page views, visitors, referrers, approximate countries, device and browser categories, and real-user performance. FollowPact does not use it to build advertising profiles. Separately, the server records a small fixed set of funnel events: waitlist joins, checkout starts, completed founding purchases, subscription starts, payment failures, refunds, and marketing unsubscribes. Those records can include sanitized UTM campaign values and an order or contact reference, but not full IP addresses, browser fingerprints, or card data.</p></section>
    <section><h2>Email choices</h2><p>The waitlist checkbox is optional marketing consent and is unchecked until you choose it. Marketing emails and essential transactional or service emails are handled separately. You can unsubscribe from marketing while still receiving receipts, access notices, payment or refund updates, security messages, and other communications necessary to provide a purchased or requested service. Replies are delivered to <a href="mailto:followpact@gmail.com">followpact@gmail.com</a>.</p></section>
    <section><h2>Retention, security, and your choices</h2><p>Information is kept only as long as reasonably needed for the purposes described, legal obligations, dispute resolution, and security. Reasonable technical and organizational safeguards are used, but no internet service can promise absolute security. To ask about access, correction, deletion, or privacy rights, email <a href="mailto:followpact@gmail.com">followpact@gmail.com</a>.</p></section>
  </PolicyShell>;
}
