import type { Metadata } from "next";
import PolicyShell from "../PolicyShell";

export const metadata: Metadata = { title: "Terms of Use | FollowPact", description: "Terms for the FollowPact preorder, private beta, subscriptions, and Client Scope-Lock service." };

export default function Terms() {
  return <PolicyShell label="Policy / Effective September 9, 2026" title="Terms of Use" intro="These terms govern the FollowPact waitlist, $9.99 founding preorder, private beta, future plans, and manual Client Scope-Lock service.">
    <section><h2>Beta and availability</h2><p>FollowPact is a pre-release product. Founders receive private-beta access with all main features by October 5, 2026. The beta is a testing version, so features may change, bugs may occur, and availability may be interrupted. The full version releases November 5, 2026.</p></section>
    <section><h2>Founding preorder</h2><p>The discounted founding preorder costs $9.99 once, approximately 55% below one month of the $21.99 regular price. It provides the benefits stated on the sales page, including temporary private-beta access and founder status. It is not a recurring subscription and does not authorize FollowPact to begin one automatically. The founding preorder closes when private beta begins on October 5, 2026. After the founding offer closes, regular access for new customers will cost $21.99 per month; founding purchases will not automatically convert to that subscription.</p></section>
    <section><h2>Future plans and founder discount</h2><p>The planned public prices are $0 per month for Free and $21.99 per month for regular access. The $9.99 founding preorder is approximately 55% below one month of the regular price and remains a one-time purchase. Private beta includes all main features, and founders receive 55% off eligible paid features. A founder who does not separately purchase or subscribe to a paid feature is not charged automatically.</p></section>
    <section><h2>Manual Client Scope-Lock</h2><p>Founding access includes up to four manual Scope-Locks, each covering one project and one structured scope document based on the project information reasonably provided. Founders may email <a href="mailto:followpact@gmail.com">followpact@gmail.com</a> to request more. Additional requests are reviewed separately and are not guaranteed by the founding purchase. Typical delivery is normally within 24 hours on business days, but unusual complexity, incomplete submissions, or service interruptions may require more time.</p><p>A Scope-Lock is prepared for review and client approval. It is not legal advice, a substitute for advice from a qualified professional, or a guarantee that a document will be legally enforceable. FollowPact does not receive or hold a freelancer&apos;s client deposit. The freelancer provides and manages their own payment link.</p></section>
    <section><h2>Acceptable use and user responsibility</h2><p>You are responsible for the accuracy and lawfulness of information you submit, for reviewing generated or manually prepared output, and for obtaining client approval. Do not use FollowPact to violate law, infringe rights, submit harmful material, probe security, evade usage controls, or interfere with the service.</p></section>
    <section><h2>Changes, cancellation, and contact</h2><p>FollowPact may reasonably change pre-release workflows, future features, usage limits, and these terms as the service develops. Material purchase implications will be communicated where appropriate. Refunds are handled under the Refund Policy and applicable law. Questions may be sent to <a href="mailto:followpactofficial@gmail.com">followpactofficial@gmail.com</a>.</p></section>
  </PolicyShell>;
}
